// Where content and audio live. Content is static JSON generated by
// tools/build-content.mjs; the service worker caches it, so a lesson you have
// opened once stays available with no network.
const base = import.meta.env.BASE_URL;

// The optional MP3 pack is ~280 MB, so a deploy usually doesn't carry it — see
// audio.js. If it is hosted somewhere separate (a CDN, object storage, another
// site), point VITE_AUDIO_BASE at it; by default the clips sit next to the app.
const withSlash = (url) => (url.endsWith('/') ? url : `${url}/`);
const audioBase = withSlash(import.meta.env.VITE_AUDIO_BASE || `${base}audio`);

export const contentUrl = (path) => `${base}content/${path}`;

/** Audio file for one clip. `aid` is stamped into the lesson JSON at build time. */
export const audioUrl = (aid, speed = 'normal') =>
  `${audioBase}${aid}${speed === 'slow' ? '-s' : ''}.mp3`;

/**
 * On-demand Finnish speech from the deployment's own function (netlify/functions).
 * Same voice as the generated pack, but nothing is stored: the CDN caches it.
 */
export const ttsUrl = (text, speed = 'normal') =>
  `${base}api/tts?text=${encodeURIComponent(text)}&speed=${speed}`;

async function getJson(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} for ${url}`);
  return res.json();
}

export const loadIndex = () => getJson(contentUrl('index.json'));

export const loadLesson = (slug) => getJson(contentUrl(`lessons/${slug}.json`));
