// Content comes from static JSON generated by tools/build-content.mjs.
// There is no API: the service worker caches these files, so a lesson you have
// opened once stays available with no network.
const base = import.meta.env.BASE_URL;

export const contentUrl = (path) => `${base}content/${path}`;

/** Audio file for one clip. `aid` is stamped into the lesson JSON at build time. */
export const audioUrl = (aid, speed = 'normal') =>
  `${base}audio/${aid}${speed === 'slow' ? '-s' : ''}.mp3`;

async function getJson(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} for ${url}`);
  return res.json();
}

export const loadIndex = () => getJson(contentUrl('index.json'));

export const loadLesson = (slug) => getJson(contentUrl(`lessons/${slug}.json`));
