import { existsSync } from 'node:fs';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

// Is a generated MP3 pack part of this build? Locally it is used if it happens to
// be there; a deploy sets VITE_NO_AUDIO_PACK to leave it out, since the pack is
// ~280 MB. Without it the app speaks with the device's own Finnish voice and never
// requests an audio file at all — the file-playing code is tree-shaken away.
const audioPack = !process.env.VITE_NO_AUDIO_PACK
  && (existsSync('client/public/audio/manifest.json') || !!process.env.VITE_AUDIO_BASE);

// The app is fully static: content is JSON generated by tools/build-content.mjs into
// client/public/content, audio is MP3 files in client/public/audio. There is no API.
export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'prompt', // never swap the app out from under a lesson in progress
      manifest: {
        name: 'Puhu suomee — spoken Finnish',
        short_name: 'Puhu suomee',
        description: 'A spoken-Finnish course: vocabulary, phrases, dialogues and role-plays, with audio.',
        lang: 'en',
        start_url: './',
        scope: './',
        display: 'standalone',
        orientation: 'portrait',
        background_color: '#ffffff',
        theme_color: '#002f6c',
        icons: [
          { src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png' },
          { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png' },
          { src: 'icons/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      workbox: {
        // Precache the app and all lesson text (~2 MB) so the whole course reads
        // offline. Audio is far too big for that and is cached per clip instead.
        globPatterns: ['**/*.{js,css,html,png,json}'],
        // The manifest icons are injected into the precache by the plugin itself;
        // globbing them too would list them twice.
        globIgnores: ['audio/**', 'icons/icon-*.png'],
        navigateFallback: 'index.html',
        cleanupOutdatedCaches: true,
        runtimeCaching: [
          {
            urlPattern: ({ url }) => url.pathname.includes('/audio/'),
            handler: 'CacheFirst',
            options: {
              cacheName: 'finnish-audio',
              rangeRequests: true, // <audio> asks for byte ranges
              cacheableResponse: { statuses: [0, 200] },
              expiration: { maxEntries: 20000, maxAgeSeconds: 60 * 60 * 24 * 365 },
            },
          },
        ],
      },
      devOptions: { enabled: false },
    }),
  ],
  define: { __AUDIO_PACK__: JSON.stringify(audioPack) },
  root: 'client',
  build: { outDir: '../dist', emptyOutDir: true },
  server: { port: 5173 },
});
